### ISSUE TITLE
The demo can't run

### ISSUE THREAD

**Issue by dongnaebi** [ryoyakawai/x-webmidi#2]
first,thanks for it is a great project,and sorry to my english so bad(from china).
when I insert my midikeyboard and restart chrome,console log is:"An attempt was made to break through the security policy of the user agent"。I have set up allow all website control midi device。
then how can I do to resolve it?

**Comment by ryoyakawai** [comment]
Hi! Do not worry about English, I am not a native Engish speaker, too :-)
The message from browser's console looks like coming from the demo is trying to access cross-domain site. Which demo are you running to get this demo? I would like to know the URL to investigate why this error is coming from.

**Comment by dongnaebi** [comment]
呵呵O(∩_∩)O~,unlucky,all of demo is the same problem,and when I copy the demo to my server online,also the same problem.but my keyboard can run in http://soundtrap.com/
